# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa9a778349feb6ef5cb05aeace372c60da394e94dfd927636c53571037eb13313c841fbb605b300f1e0f6091caf7e48a3ea67a92f2e02e9c6a6f997a170b6807

test:
  secret_key_base: dd63a8a670e3d930067e95dbf2d74619dd03ca81f56b6e6555ff308a361bedf22fd1d10c1454eb86c5b0264eebddf6fd41975ca0a6527840f6dbd8b834147363

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
