# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86f1e2e352df1e05bba9bb7ab15171e07aff4530403b18e9d68fef834eb0e398190a7076b4c7acb4053f75d0aa37b6053b81775c5302d55844ff78bcb0b981b9

test:
  secret_key_base: 4cdf6406279497226aac2cdb3f9b073db2a2b031a6c39f4519e4c093b5215ef2c7f23e66d04f0a162608df53f8370e1a212f195286b7caec4536812002bf8e45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
